#pragma once

#include "HDC2080.h"
#include <Wire.h>

const uint8_t ADDR = 0x40;// address for all of the sensors
                // are the same, 0x40 so we emplore the use
                // of a multiplexer to get data to and from the 
                //sensors

class Sensor{
    private: 
    //Going to change to the addr of the multiplexer as that will be a hub for the sensors and will facilitate the communication between 
    // the mcu and the sensors
    HDC2080 sensor = HDC2080(ADDR);//initializes all the sensors with the same addrs as they are the same;
        uint8_t bus;
        void Multiplexer (uint8_t bus);
        float lowTemp,highTemp, lowHumidity, highHumidity;
    public : 
            
    Sensor(uint8_t bus);
    void setTempRange( float lowTemp, float highTemp);//sets the threshold for the temperature readings
    void setHumidityRange(float lowHumidity,float highHumidity); //sets the threshold for the humidity readings
    float readTemp();//reads the temperature value generated by the sensor
    float readHumidity();//reads the humidity calue generated by the sensor
    void refreshSensor(uint8_t duration);//enables and disables the heating element of the sensor for a set time to ensure accurate readings
    void sensorInit();


};
